### ISSUE TITLE
Link section still appears after removing Links

### ISSUE THREAD

**Issue by ariesps** [darklinkpower/Helium#13]
I've detected thath sometimes when I remove all links from a game,  in detail view, it still shows the background of link section.
It usually happens when metadata is downloaed from sources, and then i remove manually all links from the game.

This is an example (above genre)
![image](https://user-images.githubusercontent.com/7125095/141192468-d67e47f4-4d8c-4880-8de4-c03211833364.png)

It seems a bit random because i have other games without links and this section is not showing up.

![image](https://user-images.githubusercontent.com/7125095/141192431-6b1e5b89-0e32-46dd-ae58-1925bf7c77d7.png)

**Comment by darklinkpower** [comment]
Fixed for next release
