### ISSUE TITLE
Round Corners Grid View

### ISSUE THREAD

**Issue by ariesps** [darklinkpower/Helium#15]
Any chance to be able to get round corners on Grid View? Maybe as an theme modifier option?

Something like this

![image](https://user-images.githubusercontent.com/7125095/141193883-15183e69-dd0b-4bb9-87b9-002b1d241451.png) ![image](https://user-images.githubusercontent.com/7125095/141194035-169ac2fb-b2de-4e01-8514-58d936f88112.png)

**Comment by darklinkpower** [comment]
Already done but forgot to close this
