### ISSUE TITLE
Cannot resize from window edge with sidebar

### ISSUE THREAD

**Issue by bburky** [darklinkpower/Helium#16]
**Describe the bug**
Minor issue: You cannot resize the window from the (left) edge easily where the sidebar buttons are. In the blank space below all of the sidebar buttons, the window can be resized fine. But if you hover your cursor over the edge of the window where there is a sidebar button, no resize arrows appear.

**To Reproduce**
Hover your cursor over the edge of the window where there is a sidebar button. No resize arrows appear on the cursor. The window cannot be resized in this area.

Move your cursor below the sidebar buttons. The edge of the window can be resized now.

**Fix?**
Somehow this isn't an issue in the default theme, even when you set the sidebar to any side of the window. Not quite sure how, I don't see any margin anywhere, I'm not sure why it works fine.

An easy fix is a margin on DockContentHolder, but I don't think that's the right way. The default theme doesn't seem to do that, maybe there's a margin on one of the other containing elements.

**Comment by darklinkpower** [comment]
Fixed, I used a small padding.
