### ISSUE TITLE
Wrap-around feature for publisher names

### ISSUE THREAD

**Issue by kaporli** [darklinkpower/Helium#17]
**Describe the solution you'd like**
Wrap-around function for long publisher names. 

Currently, there's a setting in theme modifier to adjust the width of the description, but not the info to the right of the description. With excessively long publisher names, I'd like the names to wrap around to a next line so I don't have any horizontal scroll bars.

**Screenshots**
![image](https://user-images.githubusercontent.com/52631424/141373877-4e14531e-3a51-4e6c-aa2e-9af419d4d761.png)

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/Helium/commit/b695bf626f03cb35f28cc81f7f9870d9ceadd1cc
