### ISSUE TITLE
Blurry/ darkened background on the games list sidebar

### ISSUE THREAD

**Issue by kaporli** [darklinkpower/Helium#18]
**Describe the solution you'd like**
I'd like a feature where the gray wall shown in the screenshot below has a transparent, darkened background like the rest of the details page. Or even better, the option to recolor the sidebar in the theme modifier addon.

**Screenshots**
![image](https://user-images.githubusercontent.com/52631424/141374269-e5c0cbe3-bc04-4f85-bfe5-d5334beae9c2.png)

**Comment by darklinkpower** [comment]
Closing as discussed on discord.
