### ISSUE TITLE
Details clipping on low resolution displays

### ISSUE THREAD

**Issue by fuenechaos** [darklinkpower/Helium#2]
The details section clips on a low resolution display  if the text is long
![image](https://user-images.githubusercontent.com/67466686/133626305-a1eadd75-926c-4fc8-a617-60412325b6ca.png)

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/Helium/commit/6ca18509e773a46d5bc3366c32d314e460ca3fe8
