### ISSUE TITLE
Bug on Grid View Group

### ISSUE THREAD

**Issue by ariesps** [darklinkpower/Helium#22]
**Describe the bug**
In grid View, when games are grouped, sometimes game image apperas on left side of the group

**To Reproduce**
Normally I can reproduce this grouping by series. Normally you have to scroll down, then it appears. 

**Screenshots**
(notice the game image left to assasins creed chronicles series).
![image](https://user-images.githubusercontent.com/7125095/146647536-10c0d218-6bea-46ed-a4e5-b8909eb6d58a.png)

**Comment by darklinkpower** [comment]
This is a bug in Playnite https://github.com/JosefNemec/Playnite/issues/2527

**Comment by ariesps** [comment]
Thanks for the info!
