### ISSUE TITLE
Cover Changer Support

### ISSUE THREAD

**Issue by ahmedady** [darklinkpower/Helium#23]
Support cover Changer from Lacro59's Background changer extinsion : https://playnite.link/forum/thread-564.html
"The theme currently support changing backgrounds but it doesn't support covers changer"

**Comment by darklinkpower** [comment]
Please fill the information using the issue template in the future.

**Comment by ahmedady** [comment]
> Please fill the information using the issue template in the future.

I haven't noticed my bad. I will make sure to use the issue template next time.

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/Helium/commit/1c1d35830685c4fc0aeba343d9da2b8a99cdd15f

Support for GridView was not added because it caused big performance issues
