### ISSUE TITLE
Steam banner display no longer working correctly after 1.22 update

### ISSUE THREAD

**Issue by sengtsan** [darklinkpower/Helium#24]
### Bug Description

I had 92:43 images for covers on desktop view. After update the cover images are now square, leaving blank space above and below the image in each time. 

### Screenshots

before update
![Untitled-min](https://user-images.githubusercontent.com/63714826/165718942-6bb87cd9-772d-45b2-8eee-427f821497ad.jpg)

after update
![Untitled-new](https://user-images.githubusercontent.com/63714826/165719150-4b236c4e-5f72-4c26-bc3c-dd3924516214.jpg)

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/Helium/commit/f40bda351d05b2d049f3eb607f0901e1e307ebbd
