### ISSUE TITLE
Grid View: Suggestion to change the default opacity of cover controls

### ISSUE THREAD

**Issue by IggniFyre** [darklinkpower/Helium#29]
### Feature Description

Right now, Helium shows the Play/Info button at all times even when you don't hover over them. I know it replicates how Steam does it, but it can make the artwork in grid view look a little messier. Maybe a ThemeModifier option to control the opacity could let people choose how much they see the Play/Info buttons, perhaps even separate opacity options for idle and when hovering over them.

### Screenshots

![image](https://user-images.githubusercontent.com/98881931/167561123-a3119a10-5ee0-47bb-997c-88b89334e579.png)

**Comment by darklinkpower** [comment]
Just adding as a note that I'm afraid that adding a ThemeModifier option is not in the plans. I'm sorry but while I make the effort of making the themes customizable to the liking of each, adding options for small things like this is difficult for me, as it means I have to make the implementation and also maintain it in the future. Also the available options are already too much already and I've been thinking of maybe removing some in the future to make it easier to maintain and manage.

So I'll have to consider if it should be kept as it is currently or change it to your suggestion.

**Comment by darklinkpower** [comment]
Changed in https://github.com/darklinkpower/Helium/commit/3be7fe68912e153a541c52ada679da712f1f052f

I thought about it and you can barely see the controls anyway so i guess it makes sense to hide them
