### ISSUE TITLE
Increasing the Maximum value of "Width of Description"

### ISSUE THREAD

**Issue by chonkyman** [darklinkpower/Helium#30]
### Feature Description

Would it be possible for you to increase the max value for description width? I have it on max and it only covers about half of the panel.

### Screenshots

![image](https://user-images.githubusercontent.com/82068249/169654175-b9500679-3651-46d3-a870-cf4e9ba14dfa.png)

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/Helium/commit/85941c7c4893a45ab0edd15d970da95815d9aab7
