### ISSUE TITLE
More Platform Banners

### ISSUE THREAD

**Issue by ariesps** [darklinkpower/Helium#31]
### Feature Description

Any chance to add Amiga banners? 

Amiga
![image](https://user-images.githubusercontent.com/7125095/175987933-fe227a8b-db6c-48ab-bdba-098d9be7e070.png)

Amiga CD32 
![image](https://user-images.githubusercontent.com/7125095/175988499-ff47b395-4995-49d8-9494-773515fad24e.png)

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/Helium/commit/e72bb4c6bd27ec94763966e2d0a8e61b65cc3e42

**Comment by ariesps** [comment]
Great, thanks! Awesome work!
