### ISSUE TITLE
Wrong icon on play button for launching/running

### ISSUE THREAD

**Issue by hitsu4yrkl** [darklinkpower/Helium#32]
### Bug Description

The icon on the Play Button besides the "Launching" and "Running" texts are unfitting for at least those two cases.

### Screenshots

currently:
![Screenshot 2022-08-01 024937](https://user-images.githubusercontent.com/82475806/182053352-4827cdad-c732-4049-b732-641494e9b4f8.png)
(newest theme release)

vs.

 expected:
![Screenshot 2022-08-01 025134](https://user-images.githubusercontent.com/82475806/182053385-78a08d27-e206-46b3-9520-8b4a612b3798.png)
(Steam)

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/Helium/commit/483d6ea34d6a6f5dc0e795ef5f71ca99c4113b36
