### ISSUE TITLE
Can't click info/play buttons if art doesn't extend behind them

### ISSUE THREAD

**Issue by Ohhhboyyy** [darklinkpower/Helium#39]
### Bug Description

In grid mode, if I am using a cover art that does not extend behind the info and play buttons, I cannot click them. They will disappear when I move my mouse off of the cover art's bottom edge.  

### To Reproduce

- go into Playnite settings
- go to Appearance > Grid view
- set Stretch mode to "Uniform" in drop down
- view your library in Grid mode
- assign cover art to a game that doesn't fill the entire dimensions of the grid (for example: I gave my SNES games original box art)
- try to move the mouse down and click the play/info buttons on highlight 

### Screenshots

![image](https://user-images.githubusercontent.com/14195586/215345390-cc9e7216-f0ec-4714-a693-217868f35ccf.png)
![image](https://user-images.githubusercontent.com/14195586/215345404-6d619745-7a02-4907-bda4-caac1f8718ea.png)

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/Helium/commit/920259be303aceb74c9d838ce6b97b962a7e2814
