### ISSUE TITLE
Change the opacity of the corner platform icons on the covers in the grid view.

### ISSUE THREAD

**Issue by Madcore** [darklinkpower/Helium#4]
**Describe the solution you'd like**
The posibility to change the opacity of the corner platform icons on the covers in the grid view, to make easier to differentiate similar games on different platforms

**Screenshots**
![image](https://user-images.githubusercontent.com/1870747/135716270-23d9200f-b210-4271-8e87-21f01347efb5.png)
Those Addams Family games are for differente platforms, but you can tell only by the corner platform icons.

**Comment by darklinkpower** [comment]
Done in v2.4
