### ISSUE TITLE
IMAGE SIZE 

### ISSUE THREAD

**Issue by stryxz** [darklinkpower/Helium#40]
### Feature Description

would be great if we can increase the image size 
![Screenshot_14](https://user-images.githubusercontent.com/53075646/220719169-153b45e5-9154-4e57-a4ae-196fe6ba0513.png)

**Comment by darklinkpower** [comment]
Which image specifically? All can be changed
In order: Background Image, Cover image, icon

![image](https://user-images.githubusercontent.com/1389286/220737575-1df4646f-1267-42d9-b79e-7222496517c6.png)
