### ISSUE TITLE
Cover Image toggle stopped working as of 1.51

### ISSUE THREAD

**Issue by JoaoPedroGNA** [darklinkpower/Helium#44]
### Bug Description

As of the most recent update (1.51) the Cover Image checkbox from Settings doesn't hide the cover on Details View anymore. Some like me may want it off because it takes up too much space and is redundant for those who use the Details to Grid View Converter extension.

### To Reproduce

Simply uncheck the Cover Image checkbox under Settings > Appearance > Details View.

### Screenshots

![Captura de tela 2023-11-01 135546](https://github.com/darklinkpower/Helium/assets/42844743/f5fc58ea-4694-4feb-86c7-0d142fc488b2)

**Comment by darklinkpower** [comment]
Hi, there has been no change to how the cover image works. It seems you must be using the Background changer extension, which the Playnite setting doesn't control so you need to disable the extension or the option to display the cover image in the extension settings.

**Comment by JoaoPedroGNA** [comment]
You're absolutely right. Apologies for not realizing it sooner! Great work on the theme, by the way. Loving it more with each update!

**Comment by darklinkpower** [comment]
No worries, glad to know that fixed it. I'm wondering if it would be a good idea to also hide the extension cover if the cover is disabled in settings to prevent this confusion.
