### ISSUE TITLE
Changing Icons in Grid Detail View?

### ISSUE THREAD

**Issue by Starzmore** [darklinkpower/Helium#51]
### Bug Description

Just started using Playnite to keep everything in order, and started using Helium because I liked that it can stick platform banners on the cover art automatically.

What I can't figure out though is how to tweak the art used for platform icons...

For example, an Amazon game uses the small icon until you hover over it... https://app.screencast.com/mDOXzVo7DNrW6 & https://app.screencast.com/GQgA3w2V1WxRa

But for an emulated title it's a platform banner... https://app.screencast.com/ukss7zmwcgmIv & https://app.screencast.com/FYp4boBb8U0Nx

Where can I change that banner to a smaller icon? Thanks!

**Comment by darklinkpower** [comment]
The buttons are from the DuplicateHider extension. I think it's using the icons you configured for the games platforms in the Playnite Library Manager, in main menu > Library.

P.S.: In the future please paste the images directly here to not need to open an external site 🙏

**Comment by Starzmore** [comment]
Thanks for getting back to me, I'll look at that tonight.
And sorry about the images thing, they were already posted there from when I posted this over on reddit.
