### ISSUE TITLE
Images become blurred when switching to a different box art aspect ratio

### ISSUE THREAD

**Issue by GermanPlasma** [darklinkpower/Helium#56]
### Bug Description

I made a thread about this on [Reddit](https://www.reddit.com/r/playnite/comments/1ayluhs/is_there_a_way_to_fix_image_quality_when/)

But I will explain this shortly as well here:

If I click on a game with, let's say, a normal 600x900 cover image, and I then click on another game that has a completely different aspect ratio, the image pictures blurred. When I then click on another game with the aspect ratio from the one I am currently on, it has better resolution. The wider the cover aspect ratio "switch", the more pixelated the big box art will look like

### To Reproduce

1. In Details view (Or grid view with your extension) Click on a game with, for example, a 600x900 cover
2. Now simply click on another game, this time however, it needs to have a wider aspect ratio. 400x352 was the size of my 3DS cover and that worked to show this issue. However, even wider aspect ratios have turned into complete pixel mash.
3. The cover image should be lower resolution, to a degree where text becomes barely legible.
4. Click on another game with the same (or similar) aspect ratio of the title you are on right now.
5. Suddenly the image looks much sharper.
6. Bonus: Now click back to the game from before, in my case, the 400x352 3DS cover from step 2. The image will be much sharper than before

### Screenshots

![Cover at Step 2](https://github.com/darklinkpower/Helium/assets/123846609/6ad90164-1298-4dae-a888-007ef38f9c80)
![Cover at Step 6](https://github.com/darklinkpower/Helium/assets/123846609/28f29022-dcfc-4ae7-9791-d7f8778235c4)

**Comment by darklinkpower** [comment]
I just checked an issue in the BackgroundChanger cover control. You need to report it to its developer.

**Comment by GermanPlasma** [comment]
Thank you! I will repost that over there, but it does seem like the creator isn't really changing it anymore.
Regardless, I was able to just disable that specific setting for covers (which I didn't even use in the first place) and now it's perfect. You're awesome!
