### ISSUE TITLE
No Background image after latest update

### ISSUE THREAD

**Issue by andromalandro** [darklinkpower/Helium#60]
### Bug Description

After updating to the latest version of the theme, prompted on the notification inside playnite, my background images are not showing up even if i have them downloaded.

### Screenshots

![Captura de pantalla 2024-09-24 220648](https://github.com/user-attachments/assets/fbae9c63-32c1-4275-8724-762f302763dc)
![Captura de pantalla 2024-09-24 220632](https://github.com/user-attachments/assets/4207d44e-fbd5-481d-ba26-fd779ea4bfc1)

**Comment by darklinkpower** [comment]
The background image has never been displayed in that panel. If you were seeing it before, that means you previously used the [Details to Grid View Converter](https://playnite.link/addons.html#ThemesDetailsViewToGridViewConverter_ef8a7226-eedc-478d-a506-92ee6c088aa3) and either disabled or uninstalled the extension. Enable/install again and verify that the theme is enabled in the extension settings.

**Comment by andromalandro** [comment]
thanks!
