### ISSUE TITLE
Recent update visual artifact

### ISSUE THREAD

**Issue by MrWheyne** [darklinkpower/Helium#62]
### Bug Description

As of version 1.59, a black rectangle is present in the information panel in Details View (or Grid View with Details to Grid extension) in place of where the Cover Image should be if the option to hide it is unchecked in Settings, probably due to changes made to drop shadow rendering shipped with the update.

Screenshot with the option **disabled**:
![image](https://github.com/user-attachments/assets/44b61d47-13b7-4d76-b8be-90d4c20cfa5d)

Screenshot with the option **enabled**:
![image](https://github.com/user-attachments/assets/b6c2ed30-e6c6-4bb2-a043-022168744e30)

The toggle itself:
![image](https://github.com/user-attachments/assets/0d2c6f16-3bdf-4ff9-93da-700444902a72)

### To Reproduce

Simply switch the aforementioned toggle off to reproduce.

**Comment by darklinkpower** [comment]
Fixed in new update.
