### ISSUE TITLE
Hide Scroll Bar

### ISSUE THREAD

**Issue by prestr** [darklinkpower/Helium#63]
### Feature Description

Would it be possible in the future to get a ThemeModifier setting to change the `VerticalScrollBarVisibility="Auto"` to `VerticalScrollBarVisibility="Hidden"`  in `DetailsViewGameOverview.xaml`? 

I like a clean look and with the size of my window I always see a scroll bar unless I edit the xaml but obviously after each theme update I need to do it again, so that's why a setting to change the behaviour would be great. 

## Auto
![Auto](https://github.com/user-attachments/assets/42aad35c-0e2d-4131-b43c-19c4e266d6d5)

## Hidden
![Hidden](https://github.com/user-attachments/assets/fdd05508-b875-4274-bcae-23fa9db037e8)

**Comment by darklinkpower** [comment]
Thank you for your suggestion. While I understand the request, it falls under a more personalized modification, please feel free to refer to the [Feature Requests note in the Readme](https://github.com/darklinkpower/Helium?tab=readme-ov-file#a-note-on-feature-requests) for more details about it and I'm sorry.
