### ISSUE TITLE
Only Time Played not working properly

### ISSUE THREAD

**Issue by aherreracies** [darklinkpower/Helium#9]
When having only time played it looks glitched, but when I activate something else that adds something in the same place (for example, last played) it looks correct.
![unknown](https://user-images.githubusercontent.com/67416451/139749410-d53696bd-e9ff-4ad1-9fc9-3eb69fde2c28.png)
![unknown (1)](https://user-images.githubusercontent.com/67416451/139749407-5786dc84-3b6c-4bfd-b522-09bb5a62b4c7.png)

**Comment by darklinkpower** [comment]
Fixed in master
